project_id: "project-df6c9b3f-5610-4979-8d5"
region: "us-central1"
cf_sa_email: "cloud-fn-sa@project-df6c9b3f-5610-4979-8d5.iam.gserviceaccount.com"
bucket: "yt-raw-comments-project-df6c9b3f-5610-4979-8d5"